{% set name = "mbovpan" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/salvadorlab/mbovpan.git"

requirements:
  host:
    - nextflow=22.10.6
  run:
    - nextflow=22.10.6
    - fastp
    - fastqc
    - samtools
    - picard
    - bwa
    - biopython
    - freebayes
    - spades
    - multiqc

test:
  source_files:
    - mbovpan.nf
  commands:
    - ls; nextflow run mbovpan.nf --help

about:
  home: "https://github.com/salvadorlab/mbovpan.git"
  summary: "nextflow pipeline for Mycobacterium bovis pangenome analysis."


extra:
  recipe-maintainers:
    - noahaus
