---
title: "mbovpan_figures"
author: "Noah Legall"
date: "11/5/2021"
output: html_document
---

setwd("mbovpan/auxilary/")

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(plotly)
```

## Runtimes 

```{r}
rt <- read.csv("snpcalling_runtimes.csv",header = FALSE)
head(rt)

rt <- subset(rt,V1 !=500)

rt %>% ggplot(aes(as.factor(V1),V2/60)) +
  geom_violin(fill = "gray") + theme_minimal() + 
  xlab("# of isolates") +
  ylab("Runtime (min)") + 
  theme(axis.title = element_text(size = 15)) 

rt %>% ggplot(aes(V1,V2/60)) +
  geom_point(fill = "gray") + theme_minimal() + 
  xlab("# of isolates") +
  ylab("Runtime (min)") + 
  geom_smooth(aes(V1,V2/60),color = "black",method="lm") +
  theme(axis.title = element_text(size = 15)) 
```

## Accessory Genome

```{r}
gene_pres_abs <- read.csv("gene_presence_absence.csv", header = TRUE, stringsAsFactors = FALSE, row.names = "Gene")
accessory_genome <- gene_pres_abs[!(is.na(gene_pres_abs$Accessory.Fragment)),]
core_genome <- gene_pres_abs[is.na(gene_pres_abs$Accessory.Fragment),]

accessory_genome_non_unique <- accessory_genome
auxil <- gene_pres_abs %>% select(2:14)

accessory_pa <- accessory_genome_non_unique %>% select(14:(ncol(accessory_genome_non_unique)))


##edit the gene presence absence to be numeric.
accessory_pa[!(accessory_pa=="")] <- 1
accessory_pa[accessory_pa==""] <- 0
accessory_pa$gene_name <- rownames(accessory_pa)

##let's transpose the dataframe by turning it into a matrix first. 
pa_transpose <- t(data.matrix(accessory_pa))
heatmap(pa_transpose, scale = "none", Rowv = NA, Colv = NA, col = c("white","blue"), main = "Mycobacterium bovis Accessory Genome",labRow = NULL,labCol = NULL)
```

```{r}
accessory_pa <- accessory_genome_non_unique %>% select(14:(ncol(accessory_genome_non_unique)))
accessory_pa[!(accessory_pa=="")] <- 1
accessory_pa[accessory_pa==""] <- 0
accessory_pa$gene_name <- rownames(accessory_pa)

long_prab <- accessory_pa %>% pivot_longer(!gene_name, names_to = "sample", values_to = "present")

long_prab %>% ggplot(aes(x=gene_name,y=sample,fill=present)) +
  geom_tile() +   scale_fill_manual(label=c("absent","present"),values=c("white","black")) +
  theme(text = element_text(size = 15),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks =element_blank(),
        legend.key = element_rect(fill = "white", colour = "black")
        ) 
```

```{r}
library("ggplot2")
prab_pca <- prcomp(pa_transpose)
variance <- (prab_pca$sdev)^2
loadings <- prab_pca$rotation
rownames(loadings) <- colnames(pa_transpose)
scores <- prab_pca$x 

varPercent <- variance/sum(variance) * 100 
prin_comp <- paste0("PC",1:10)
data <- data.frame(prin_comp,varPercent[1:10])
ggplot(data, aes(x=reorder(prin_comp, -varPercent[1:10]), y=varPercent[1:10], )) +
  geom_bar(stat = "identity",fill='steelblue', color="steelblue") +
  geom_text(aes(label=paste0(signif(varPercent[1:10],3)," %")), vjust=1.6, color="white", size=3.5) +
  labs(x = "Principal Components", y= "% of Explained Variance") +
  ggtitle("PCA - Scree Plot") +
  theme_minimal()

mbov_meta <- read.csv("UK_meta.csv",header = TRUE, stringsAsFactors = FALSE)

scores <- as.data.frame(scores[,1:5])
scores$country <- mbov_meta$Country
scores$species <- mbov_meta$Species
scores$instrument <- mbov_meta$Instrument

country.clust <- ggplot(as.data.frame(scores),aes(x=PC1,y=PC2, fill = country, col = country)) +
  geom_point() +
  theme_minimal()

species.clust <- ggplot(as.data.frame(scores),aes(x=PC1,y=PC2, fill = species, col = species)) +
  geom_point() +
  theme_minimal()

fig <- plot_ly(scores, x = ~PC1, y = ~PC2, z = ~PC3, color = ~species, colors = c('#BF382A', '#0C4B8E'))
```